# Generated by Django 5.2.5 on 2025-08-10 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(choices=[('g', 'grams'), ('ml', 'milliliters'), ('kg', 'kilograms'), ('oz', 'ounces'), ('lb', 'pounds'), ('l', 'liters')], max_length=50)),
                ('calories_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('protein_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbohydrates_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fats_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fiber_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='recipes/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('g', 'grams'), ('ml', 'milliliters'), ('kg', 'kilograms'), ('oz', 'ounces'), ('lb', 'pounds'), ('l', 'liters')], max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
